/**
 * generator.js
 * Pure function — reads `state` + package definitions, returns a shell script string.
 * No DOM, no side effects.
 */

function generateScript() {
  const lines = [];

  lines.push('#!/usr/bin/env bash');
  lines.push('# Ubuntu Restore — generated by ubuntu-restore.app');
  lines.push('# Generated: ' + new Date().toISOString().split('T')[0]);
  lines.push('#');
  lines.push('# Usage: chmod +x install.sh && ./install.sh');
  lines.push('');
  lines.push('set -euo pipefail');
  lines.push('');
  lines.push('# ── Sanity checks ────────────────────────────────────────────────────────────');
  lines.push('if [[ "$(id -u)" -eq 0 ]]; then echo "Do not run as root." && exit 1; fi');
  lines.push('if ! grep -qi ubuntu /etc/os-release 2>/dev/null; then echo "Ubuntu only." && exit 1; fi');
  lines.push('sudo -v');
  lines.push('');

  // System
  if (state.sysUpdate || state.sysDeps) {
    lines.push('# ── System Update ────────────────────────────────────────────────────────────');
    if (state.sysUpdate) {
      lines.push('echo "→ Updating system..."');
      lines.push('sudo apt update -y && sudo apt upgrade -y');
    }
    if (state.sysDeps) {
      lines.push('echo "→ Installing base dependencies..."');
      lines.push('sudo apt install -y \\');
      lines.push('  software-properties-common apt-transport-https ca-certificates \\');
      lines.push('  curl wget gnupg lsb-release unzip git-all');
    }
    lines.push('');
  }

  // PHP
  if (state.phpVersions.length > 0) {
    lines.push('# ── PHP ─────────────────────────────────────────────────────────────────────');
    lines.push('echo "→ Adding Ondrej PHP PPA..."');
    lines.push('sudo add-apt-repository ppa:ondrej/php -y');
    lines.push('sudo apt update -y');
    lines.push('');
    state.phpVersions.forEach(v => {
      lines.push(`echo "→ Installing PHP ${v}..."`);
      lines.push(`sudo apt install -y php${v} php${v}-cli php${v}-common libapache2-mod-php${v} || true`);
      if (state.phpExtensions.length > 0) {
        const pkgs = state.phpExtensions.map(e => `php${v}-${e}`).join(' ');
        lines.push(`sudo apt install -y ${pkgs} || true`);
      }
    });
    lines.push('');
  }

  // Generic section emitter — looks up each value in the definition array
  function emitSection(heading, selected, definitions) {
    if (!selected || selected.length === 0) return;
    const bar = '─'.repeat(Math.max(0, 76 - heading.length));
    lines.push(`# ── ${heading} ${bar}`);
    selected.forEach(value => {
      const pkg = definitions.find(d => d.value === value);
      if (pkg) pkg.lines.forEach(l => lines.push(l));
    });
    lines.push('');
  }

  emitSection('Databases',        state.dbs,        DATABASES);
  emitSection('Languages',        state.langs,       LANGUAGES);

  // Web server (single-select)
  if (state.webserver && state.webserver !== 'None') {
    const ws = WEB_SERVERS.find(w => w.value === state.webserver);
    if (ws && ws.lines.length) {
      lines.push('# ── Web Server ──────────────────────────────────────────────────────────────');
      ws.lines.forEach(l => lines.push(l));
      lines.push('');
    }
  }

  emitSection('DB Tools',         state.dbtools,     DB_TOOLS);
  emitSection('Editors',          state.editors,     EDITORS);
  emitSection('IDEs',             state.ides,        IDES);
  emitSection('VCS Tools',        state.vcs,         VCS_TOOLS);
  emitSection('Browsers',         state.browsers,    BROWSERS);
  emitSection('Containers',       state.containers,  CONTAINERS);
  emitSection('Cloud & IaC',      state.cloud,       CLOUD);
  emitSection('CLI Tools',        state.cli,         CLI_TOOLS);
  emitSection('Dev Tools',        state.devtools,    DEV_TOOLS);
  emitSection('Networking',       state.networking,  NETWORKING);
  emitSection('Security',         state.security,    SECURITY);
  emitSection('AI / ML',          state.aiml,        AI_ML);
  emitSection('Apps',             state.apps,        APPS);
  emitSection('Media & Graphics', state.media,       MEDIA);
  emitSection('Fonts',            state.fonts,       FONTS);
  emitSection('GNOME',            state.gnome,       GNOME_TOOLS);

  // Footer
  lines.push('# ── Done ─────────────────────────────────────────────────────────────────────');
  lines.push('echo ""');
  lines.push('echo "✓ Installation complete!"');
  if (state.dbs.includes('MariaDB') || state.dbs.includes('MySQL')) {
    lines.push('echo "! Run: sudo mysql_secure_installation"');
  }
  if (state.containers.includes('Docker Engine')) {
    lines.push('echo "! Log out and back in for Docker group membership."');
  }
  if (state.networking.includes('Wireshark')) {
    lines.push('echo "! Log out and back in for Wireshark group membership."');
  }

  return lines.join('\n');
}
