const state = {
  sysUpdate:     true,
  sysDeps:       true,
  phpVersions:   [],
  phpExtensions: ['mysql', 'curl', 'gd', 'mbstring', 'xml', 'zip', 'intl'],
  dbs:           [],
  langs:         [],
  webserver:     'None',
  dbtools:       [],
  editors:       [],
  ides:          [],
  vcs:           [],
  browsers:      [],
  containers:    [],
  cloud:         [],
  cli:           [],
  devtools:      [],
  networking:    [],
  security:      [],
  aiml:          [],
  apps:          [],
  media:         [],
  graphics:      [],
  fonts:         [],
  gnome:         [],
};
